INSERT INTO language_ (id, name, typeType, compilingType, date, creator, paradigm, purpose, numberOfJobs, imagePath, isTheOne)
VALUES (1,'8th', 'DYNAMIC', 'INTERPRETED', 2008,'Ron Aaron', 'MULTIPARADIGM', 'Embedded Systems', 1000,'',false),
       (2,'AWK', 'DYNAMIC', 'INTERPRETED', 1977, 'Alfred Aho', 'MULTIPARADIGM', 'Text Processing',100,'',false),
       (3,'ABAP', 'STATIC', 'COMPILED', 1980, 'SAP SE', 'OOP', 'ERP', 5000,'',false),
       (4,'Ballerina', 'STATIC', 'COMPILED', 2017, 'WSO2', 'MULTIPARADIGM', 'ERP', 1000,'',false),
       (5,'C', 'STATIC', 'COMPILED', 1970, 'Dennis Ritchie', 'IMPERATIVE', 'OS', 10000,'',false),
       (6,'Bash','DYNAMIC','INTERPRETED',1987,'Brian Fox','MULTIPARADIGM','Scripting',25000,'',false),
       (7,'C#', 'STATIC', 'COMPILED', 2000, 'Microsoft', 'MULTIPARADIGM', 'APP development',25000,'',false),
       (8, 'C++','STATIC','COMPILED',1983,'Bjarne Stroustrup','MULTIPARADIGM','OS', 25000,'',false),
       (9, 'CFML','DYNAMIC','INTERPRETED',1995,'Jeremy Allaire','MULTIPARADIGM','APP development',1000,'',false),
       (10,'Clojure','DYNAMIC','COMPILED',2007,'Rich Hickey','MULTIPARADIGM','APP development',	1000,'',false),
       (11,'ClojureScript','DYNAMIC','COMPILED',2011,'David Nolen','MULTIPARADIGM','Frontend',1000,'',false),
       (12,'Cobol','STATIC','COMPILED',1959,'Grace Hopper','IMPERATIVE','Accounting',5000,'',false),
       (13,'CoffeeScript','DYNAMIC','COMPILED',2009,'Jeremy Ashkenas','MULTIPARADIGM','Frontend',1000,'',false),
       (14,'Lisp', 'DYNAMIC', 'BOTH', 1958,'John McCarthy', 'MULTIPARADIGM', 'AI', 5000,'',false),
       (15, 'Crystal','STATIC', 'COMPILED', 2014, 'Ary Borenszweig', 'MULTIPARADIGM', 'Backend', 5000,'',false),
       (16, 'D', 'STATIC', 'COMPILED', 2001,' Walter Bright', 'MULTIPARADIGM', 'Ambiguous', 1000,'',false),
       (17,'Dart', 'BOTH', 'COMPILED', 2011, 'Google', 'MULTIPARADIGM', 'Frontend', 10000,'',false),
       (18,'Delphi Pascal','STATIC','COMPILED',1995,'Anders Hejlsberg','OOP','DDBB',1000,'',false),
       (19, 'Elixir','DYNAMIC','COMPILED',2011,'José Valim','FUNCTIONAL','Distributed Systems',5000,'',false),
       (20,'Elm','STATIC','COMPILED',2012,'Evan Czaplicki','FUNCTIONAL','Frontend',	5000,'',false),
       (21, 'Erlang','DYNAMIC','BOTH',	1980,'Joe Armstrong','FUNCTIONAL','Distributed Systems',	5000,'',false),
       (22,'F#','STATIC','COMPILED',2002,'Microsoft','FUNCTIONAL','APP development',5000,'',false),
       (23,'Fortran','STATIC','COMPILED',1957,'IBM','PROCEDURAL','Scientific',10000,'',false),
       (24, 'Gleam','STATIC','COMPILED',2017,'Louis Pilfold','FUNCTIONAL','Distributed Systems',1000,'',false),
       (25, 'Go','STATIC','COMPILED',2007,'Google','MULTIPARADIGM','SO',10000,'',false),
       (26,'Groovy','DYNAMIC','BOTH',	2003,'Apache','MULTIPARADIGM','APP development',10000,'',false),
       (27, 'Haskell','STATIC','COMPILED',1990,'Philip Wadler','FUNCTIONAL','Scientific',1000,'',false),
       (28,'Java','STATIC','BOTH',1995,'Sun Microsystems','MULTIPARADIGM','Backend',25000,'',false),
       (29,'JavaScript','STATIC','INTERPRETED',1995,'Netscape Communications','MULTIPARADIGM','Frontend',25000,'',TRUE),
       (30,'jq','DYNAMIC','INTERPRETED',2012,'Stephen Dolan','FUNCTIONAL','Backend',500,'',false),
       (31,'Julia',	'DYNAMIC',	'BOTH',	2009,'Stefan Karpinski','MULTIPARADIGM','Scientific',1000,'',false),
       (32,'Kotlin','STATIC','BOTH',2011,'JetBrains','MULTIPARADIGM','Android',5000,'',false),
       (33,'LFE','STATIC','BOTH',2008,'Robert Virding','FUNCTIONAL','Distribued Systems',500,'',false),
       (34, 'Lua','DYNAMIC','BOTH',1993,'Roberto Ierusalimschy'	,'MULTIPARADIGM','Scripting',1000,'',false),
       (35, 'MIPS Assembly','NO','NO',1981,'Stanford University','IMPERATIVE','Embedded Systems',5000,'',false),
       (36,'Nim','STATIC','COMPILED',2008,'Andreas Rumpf',	'MULTIPARADIGM','APP development',1000,'',false),
       (37,'Objective-C','STATIC','COMPILED',1980,'Brad Cox.',	'OOP','IOS',5000,'',false),
       (38, 'OCaml','STATIC','COMPILED',1996,'Paris University','MULTIPARADIGM','Scientific',500,'',false),
       (39,'Perl','DYNAMIC','INTERPRETED',	1987,'Larry Wall','MULTIPARADIGM',	'Text Processing',1000,'',false),
       (40,'PHP','DYNAMIC','INTERPRETED',1994,'Rasmus Lerdorf','MULTIPARADIGM',	'Backend',25000,'',false),
       (41,'Pharo','DYNAMIC','INTERPRETED',2008,'Marcus Denker','MULTIPARADIGM','APP development',5000,'',false),
       (42,'PL/SQL','STATIC','COMPILED',1980,'Oracle Corporation','PROCEDURAL',	'DDBB',25000,'',false),
       (43,'Prolog','DYNAMIC','INTERPRETED',1970,'Alain Colmerauer','IMPERATIVE','Expert Systems',500,'',false),
       (44,'PureScript','STATIC','COMPILED',2013,'Phil Freeman','FUNCTIONAL',	'Frontend',	500,'',false),
       (45, 'Python','DYNAMIC','INTERPRETED',1991,'Guido van Rossum','MULTIPARADIGM','Data Analysis',25000,'',false),
       (46, 'R','DYNAMIC','INTERPRETED',1993,'Robert Gentleman','MULTIPARADIGM','Data Analysis'	,1000,'',false),
       (47, 'Racket','STATIC','BOTH',1995,'MIT','MULTIPARADIGM','Scientific', 500,'',false),
       (48, 'Raku',	'DYNAMIC','BOTH',2001,'Larry Wall','MULTIPARADIGM','APP development',1000,'',false),
       (49, 'ReasonML',	'STATIC','COMPILED',2017,'Jordan Walke','FUNCTIONAL','APP development',500,'',false),
       (50, 'Red','DYNAMIC','INTERPRETED',2009,'Nenad Rakocevic','MULTIPARADIGM','UI development',500,'',false),
       (51,'Ruby','DYNAMIC','INTERPRETED',	1995,'Yukihiro Matsumoto','MULTIPARADIGM','Backend',	10000,'',false),
       (52,'Rust','STATIC',	'COMPILED',	2010,'Graydon Hoare','MULTIPARADIGM','SO',	5000,'',false),
       (53,'Scala',	'STATIC','BOTH',2001,'Martin Odersky','MULTIPARADIGM','Accounting',	25000,'',false),
       (54,'Scheme','DYNAMIC','INTERPRETED',1970,'MIT', 'MULTIPARADIGM'	,'Teaching',500,'',false),
       (55, 'Standard ML','STATIC','COMPILED',1983,'Edimburg University','MULTIPARADIGM','Scientific',500,'',false),
       (56,'Swift',	'STATIC','COMPILED',2014,'Apple','MULTIPARADIGM','IOS',	25000,'',false),
       (57,'Tcl','DYNAMIC','BOTH',	1988,'John Ousterhout',	'MULTIPARADIGM','Scripting',500,'',false),
       (58,'TypeScript','STATIC','BOTH',2012,'Anders Hejlsberg','MULTIPARADIGM'	,'Frontend',25000,'',false),
       (59,'Unison'	,'STATIC','COMPILED',2015,'Rúnar Bjarnason'	,'FUNCTIONAL',	'Arquives Sync',500,'',false),
       (60, 'V','STATIC','COMPILED',2018,'Alex Medvednikov','MULTIPARADIGM','SO',500,'',false),
       (61, 'Visual Basic',	'STATIC','COMPILED',2002,'Microsoft','OOP',	'APP development',10000,'',false),
       (62, 'WebAssembly',	'STATIC','COMPILED',2015,'Mozilla',	'MULTIPARADIGM','Frontend',1000,'',false),
       (63, 'Wren',	'DYNAMIC','INTERPRETED',2017,'Ryan J. Gordon',	'MULTIPARADIGM','Video Games',	1000,'',false),
       (64, 'x86-64 Assembly','STATIC',	'NO',2003,	'Intel','IMPERATIVE','SO',1000,'',false),
       (65, 'Zig',	'STATIC','COMPILED',2015,'Andrew Kelley','MULTIPARADIGM','APP development'	,500,'',false),
       (66, 'PostScript','STATIC',	'BOTH',1982,'Adobe','MULTIPARADIGM','Graphics',500,'',false),
       (67,'Curry',	'STATIC','COMPILED',1990,'Universidad de Kiel','FUNCTIONAL'	,'Teaching',500,'',false),
       (68,'MatLab','DYNAMIC','INTERPRETED',1970,'Cleve Moler','MULTIPARADIGM','Scientific',500,'',false),
       (69,'Octave','DYNAMIC','INTERPRETED',1988,'John W. Eaton','MULTIPARADIGM','Accounting'	,500,'',false);
