INSERT INTO language_ (id, name, typeType, compilingType, date, creator, paradigm, purpose, numberOfJobs, imagePath, isTheOne)
VALUES (1,'8th', 'DYNAMIC', 'INTERPRETED', 2008,'Ron Aaron', 'MULTIPARADIGM', 'Embedded Systems', 1000,'images/8th.jpg',false),
       (2,'AWK', 'DYNAMIC', 'INTERPRETED', 1977, 'Alfred Aho', 'MULTIPARADIGM', 'Text Processing',100,'images/awk.jpg',false),
       (3,'ABAP', 'STATIC', 'COMPILED', 1980, 'SAP SE', 'OOP', 'ERP', 5000,'images/abaP.jpg',false),
       (4,'Ballerina', 'STATIC', 'COMPILED', 2017, 'WSO2', 'MULTIPARADIGM', 'ERP', 1000,'images/ballerina.jpg',false),
       (5,'C', 'STATIC', 'COMPILED', 1970, 'Dennis Ritchie', 'IMPERATIVE', 'OS', 10000,'images/c.jpg',false),
       (6,'Bash','DYNAMIC','INTERPRETED',1987,'Brian Fox','MULTIPARADIGM','Scripting',25000,'images/bash.jpg',false),
       (7,'C#', 'STATIC', 'COMPILED', 2000, 'Microsoft', 'MULTIPARADIGM', 'APP development',25000,'images/csharp.jpg',false),
       (8, 'C++','STATIC','COMPILED',1983,'Bjarne Stroustrup','MULTIPARADIGM','OS', 25000,'images/cpp_logo.jpg',false),
       (9, 'CFML','DYNAMIC','INTERPRETED',1995,'Jeremy Allaire','MULTIPARADIGM','APP development',1000,'images/cfml.jpg',false),
       (10,'Clojure','DYNAMIC','COMPILED',2007,'Rich Hickey','MULTIPARADIGM','APP development',	1000,'images/clojure.jpg',false),
       (11,'ClojureScript','DYNAMIC','COMPILED',2011,'David Nolen','MULTIPARADIGM','Frontend',1000,'images/clojurescript.jpg',false),
       (12,'Cobol','STATIC','COMPILED',1959,'Grace Hopper','IMPERATIVE','Accounting',5000,'images/cobol.jpg',false),
       (13,'CoffeeScript','DYNAMIC','COMPILED',2009,'Jeremy Ashkenas','MULTIPARADIGM','Frontend',1000,'images/coffeescript.jpg',false),
       (14,'Lisp', 'DYNAMIC', 'BOTH', 1958,'John McCarthy', 'MULTIPARADIGM', 'AI', 5000,'images/lisp.jpg',false),
       (15, 'Crystal','STATIC', 'COMPILED', 2014, 'Ary Borenszweig', 'MULTIPARADIGM', 'Backend', 5000,'images/crystal.jpg',false),
       (16, 'D', 'STATIC', 'COMPILED', 2001,' Walter Bright', 'MULTIPARADIGM', 'Ambiguous', 1000,'images/D.jpg',false),
       (17,'Dart', 'BOTH', 'COMPILED', 2011, 'Google', 'MULTIPARADIGM', 'Frontend', 10000,'images/dart.jpg',false),
       (18,'Delphi Pascal','STATIC','COMPILED',1995,'Anders Hejlsberg','OOP','DDBB',1000,'images/delphi-pascal.jpg',false),
       (19, 'Elixir','DYNAMIC','COMPILED',2011,'José Valim','FUNCTIONAL','Distributed Systems',5000,'images/elixir.jpg',false),
       (20,'Elm','STATIC','COMPILED',2012,'Evan Czaplicki','FUNCTIONAL','Frontend',	5000,'images/elm.jpg',false),
       (21, 'Erlang','DYNAMIC','BOTH',	1980,'Joe Armstrong','FUNCTIONAL','Distributed Systems',5000,'images/erlang.jpg',false),
       (22,'F#','STATIC','COMPILED',2002,'Microsoft','FUNCTIONAL','APP development',5000,'images/fsharp.jpg',false),
       (23,'Fortran','STATIC','COMPILED',1957,'IBM','PROCEDURAL','Scientific',10000,'images/dortran.jpg',false),
       (24, 'Gleam','STATIC','COMPILED',2017,'Louis Pilfold','FUNCTIONAL','Distributed Systems',1000,'images/gleam.jpg',false),
       (25, 'Go','STATIC','COMPILED',2007,'Google','MULTIPARADIGM','SO',10000,'images/go.jpg',false),
       (26,'Groovy','DYNAMIC','BOTH',	2003,'Apache','MULTIPARADIGM','APP development',10000,'images/groovy.jpg',false),
       (27, 'Haskell','STATIC','COMPILED',1990,'Philip Wadler','FUNCTIONAL','Scientific',1000,'images/haskell.jpg',false),
       (28,'Java','STATIC','BOTH',1995,'Sun Microsystems','MULTIPARADIGM','Backend',25000,'images/java.jpg',false),
       (29,'JavaScript','STATIC','INTERPRETED',1995,'Netscape Communications','MULTIPARADIGM','Frontend',25000,'images/js.jpg',TRUE),
       (30,'jq','DYNAMIC','INTERPRETED',2012,'Stephen Dolan','FUNCTIONAL','Backend',500,'images/jq.jpg',false),
       (31,'Julia',	'DYNAMIC',	'BOTH',	2009,'Stefan Karpinski','MULTIPARADIGM','Scientific',1000,'images/julia.jpg',false),
       (32,'Kotlin','STATIC','BOTH',2011,'JetBrains','MULTIPARADIGM','Android',5000,'images/kotlin.jpg',false),
       (33,'LFE','STATIC','BOTH',2008,'Robert Virding','FUNCTIONAL','Distribued Systems',500,'images/lfe.jpg',false),
       (34,'Lua','DYNAMIC','BOTH',1993,'Roberto Ierusalimschy'	,'MULTIPARADIGM','Scripting',1000,'images/lua.jpg',false),
       (35,'MIPS Assembly','NO','NO',1981,'Stanford University','IMPERATIVE','Embedded Systems',5000,'images/mips.png',false),
       (36,'Nim','STATIC','COMPILED',2008,'Andreas Rumpf',	'MULTIPARADIGM','APP development',1000,'images/nim.jpg',false),
       (37,'Objective-C','STATIC','COMPILED',1980,'Brad Cox.',	'OOP','IOS',5000,'images/obj-c.jpg',false),
       (38,'OCaml','STATIC','COMPILED',1996,'Paris University','MULTIPARADIGM','Scientific',500,'images/ocaml.jpg',false),
       (39,'Perl','DYNAMIC','INTERPRETED',	1987,'Larry Wall','MULTIPARADIGM',	'Text Processing',1000,'images/perl.jpg',false),
       (40,'PHP','DYNAMIC','INTERPRETED',1994,'Rasmus Lerdorf','MULTIPARADIGM',	'Backend',25000,'images/php.jpg',false),
       (41,'Pharo','DYNAMIC','INTERPRETED',2008,'Marcus Denker','MULTIPARADIGM','APP development',5000,'images/pharo.jpg',false),
       (42,'SQL','STATIC','COMPILED',1980,'Oracle Corporation','PROCEDURAL',	'DDBB',25000,'images/sql.jpg',false),
       (43,'Prolog','DYNAMIC','INTERPRETED',1970,'Alain Colmerauer','IMPERATIVE','Expert Systems',500,'images/prolog.jpg',false),
       (44,'PureScript','STATIC','COMPILED',2013,'Phil Freeman','FUNCTIONAL',	'Frontend',	500,'images/purescript.png',false),
       (45, 'Python','DYNAMIC','INTERPRETED',1991,'Guido van Rossum','MULTIPARADIGM','Data Analysis',25000,'images/python.jpg',false),
       (46, 'R','DYNAMIC','INTERPRETED',1993,'Robert Gentleman','MULTIPARADIGM','Data Analysis'	,1000,'images/r.jpg',false),
       (47, 'Racket','STATIC','BOTH',1995,'MIT','MULTIPARADIGM','Scientific', 500,'images/racket.jpg',false),
       (48, 'Raku',	'DYNAMIC','BOTH',2001,'Larry Wall','MULTIPARADIGM','APP development',1000,'images/raku.jpg',false),
       (49, 'ReasonML',	'STATIC','COMPILED',2017,'Jordan Walke','FUNCTIONAL','APP development',500,'images/reasonml.jpg',false),
       (50, 'Red','DYNAMIC','INTERPRETED',2009,'Nenad Rakocevic','MULTIPARADIGM','UI development',500,'images/red.jpg',false),
       (51,'Ruby','DYNAMIC','INTERPRETED',	1995,'Yukihiro Matsumoto','MULTIPARADIGM','Backend',	10000,'images/ruby.jpg',false),
       (52,'Rust','STATIC',	'COMPILED',	2010,'Graydon Hoare','MULTIPARADIGM','SO',	5000,'images/rust.jpg',false),
       (53,'Scala',	'STATIC','BOTH',2001,'Martin Odersky','MULTIPARADIGM','Accounting',	25000,'images/scala.jpg',false),
       (54,'Scheme','DYNAMIC','INTERPRETED',1970,'MIT', 'MULTIPARADIGM'	,'Teaching',500,'images/scheme.png',false),
       (55, 'Standard ML','STATIC','COMPILED',1983,'Edimburg University','MULTIPARADIGM','Scientific',500,'images/standar ml.jpg',false),
       (56,'Swift',	'STATIC','COMPILED',2014,'Apple','MULTIPARADIGM','IOS',	25000,'images/swift.jpg',false),
       (57,'Tcl','DYNAMIC','BOTH',	1988,'John Ousterhout',	'MULTIPARADIGM','Scripting',500,'images/tcl.png',false),
       (58,'TypeScript','STATIC','BOTH',2012,'Anders Hejlsberg','MULTIPARADIGM'	,'Frontend',25000,'images/typescript.jpg',false),
       (59,'Unison'	,'STATIC','COMPILED',2015,'Rúnar Bjarnason'	,'FUNCTIONAL',	'Arquives Sync',500,'images/unison.jpg',false),
       (60, 'V','STATIC','COMPILED',2018,'Alex Medvednikov','MULTIPARADIGM','SO',500,'images/v.jpg',false),
       (61, 'Visual Basic',	'STATIC','COMPILED',2002,'Microsoft','OOP',	'APP development',10000,'images/vb.jpg',false),
       (62, 'WebAssembly',	'STATIC','COMPILED',2015,'Mozilla',	'MULTIPARADIGM','Frontend',1000,'images/webassembly.png',false),
       (63, 'Wren',	'DYNAMIC','INTERPRETED',2017,'Ryan J. Gordon',	'MULTIPARADIGM','Video Games',	1000,'images/wren.jpg',false),
       (64, 'x86-64 Assembly','STATIC',	'NO',2003,	'Intel','IMPERATIVE','SO',1000,'images/assmebly.png',false),
       (65, 'Zig',	'STATIC','COMPILED',2015,'Andrew Kelley','MULTIPARADIGM','APP development'	,500,'images/zig.jpg',false),
       (66, 'PostScript','STATIC',	'BOTH',1982,'Adobe','MULTIPARADIGM','Graphics',500,'images/postscript.jpg',false),
       (67,'Curry',	'STATIC','COMPILED',1990,'Universidad de Kiel','FUNCTIONAL'	,'Teaching',500,'images/curry.png',false),
       (68,'MatLab','DYNAMIC','INTERPRETED',1970,'Cleve Moler','MULTIPARADIGM','Scientific',500,'images/matlab.jpg',false),
       (69,'Octave','DYNAMIC','INTERPRETED',1988,'John W. Eaton','MULTIPARADIGM','Accounting'	,500,'images/octave.jpg',false);
